### ISSUE TITLE
Add driver for Rust

### ISSUE THREAD

**Issue by DavidBM** [mlewis7127/awesome-qldb#3]
Hi! 

We developed and QLDB driver in Rust. We are using it internally, so we will keep the development.

https://github.com/Couragium/qldb-rs

Would you like to add it o the list?

**Comment by mlewis7127** [comment]
No worries. I've separated out the QLDB drivers section into the official AWS drivers, and now a new category of the community supported drivers. Will definitely have to try this out soon

**Comment by mlewis7127** [comment]
The QLDB driver in Rust link has been added

**Comment by DavidBM** [comment]
Nice! If you try it let me know! 

Ohh, I see that there is a ion section too.

We developed our own ion oarser/encoder/hasher for the driver. 

https://github.com/Couragium/ion-binary-rs
